# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('city', models.CharField(max_length=40, verbose_name='Ciudad')),
                ('verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('ingress_nick', models.CharField(max_length=30, verbose_name='Ingress Nick')),
                ('ingress_nivel', models.IntegerField(default=0, verbose_name='Ingress Nivel')),
                ('telegram_nick', models.CharField(max_length=30, verbose_name='Telegram Nick')),
                ('telegram_id', models.IntegerField(default=0, verbose_name='Telegram ID')),
                ('geo_latitude', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Latitud')),
                ('geo_longitude', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Longitud')),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='factions', verbose_name='Imagen/Logo')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adaapp.Faction'),
        ),
    ]
