# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adaapp', '0002_auto_20160901_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='ingress_nivel',
            new_name='ingress_level',
        ),
    ]
