# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaapp', '0006_agent_verified_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='profile_picture',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Foto Perfil'),
        ),
    ]
